// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build integration

package integration

// Test plan: lifecycle/test-plans/onboarding-architecture-selection-5-test.md
// — Milestone 6 (FR-17, FR-18): the opt-in scaffolding hand-off seam degrades
// gracefully while no Scaffolder is registered (the state of this codebase
// today — see internal/architecture/scaffold.go), and the core wizard commit
// flow never depends on it.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kaos-control/kaos-control/internal/architecture"
	"github.com/kaos-control/kaos-control/internal/directives"
)

// TestWizardScaffold_DirectivesScaffolder_GeneratesDirectiveFiles covers the
// production wiring (main.go registers directives.Scaffolder): with it
// registered, GET reports available and POST generates the directive files
// for the promoted stack. Uses the real shipped catalog so the promoted
// go-vue.md carries a stack_profile for Generate to read. Registration is
// undone in cleanup so the no-scaffolder tests above are unaffected.
func TestWizardScaffold_DirectivesScaffolder_GeneratesDirectiveFiles(t *testing.T) {
	architecture.RegisterScaffolder(directives.Scaffolder{})
	t.Cleanup(func() { architecture.RegisterScaffolder(nil) })

	env := newTestEnvWithScaffold(t, nil)

	// Commit so the chosen stack is promoted — Generate reads the promoted
	// stack profile from disk.
	commit := env.doRequest("POST", "/api/p/testproject/architecture/wizard/commit",
		wizardCommitReq("architectures/modular-monolith.md", "tech-stacks/go-vue.md", nil, nil, nil))
	requireStatus(t, commit, 200)
	commit.Body.Close()

	getResp := env.doRequest("GET",
		"/api/p/testproject/architecture/wizard/scaffold?architecture=modular-monolith&tech_stack=go-vue", nil)
	requireStatus(t, getResp, 200)
	if available, _ := readJSON(t, getResp)["available"].(bool); !available {
		t.Fatal("expected available=true with the directives scaffolder registered")
	}

	postResp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{{"step_key": "agent-directives", "use_defaults": true, "selected": true}},
	})
	requireStatus(t, postResp, 200)
	postData := readJSON(t, postResp)
	if available, _ := postData["available"].(bool); !available {
		t.Fatal("expected available=true on scaffold run")
	}

	for _, f := range []string{"AGENTS.md", "CLAUDE.md"} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, f)); err != nil {
			t.Errorf("expected %s generated by the scaffold run: %v", f, err)
		}
	}

	// Build/lint/test pipelines are bootstrapped from the promoted stack's
	// stack_profile into lifecycle/devops/.
	for _, f := range []string{"build.yaml", "lint.yaml", "test.yaml"} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, "lifecycle", "devops", f)); err != nil {
			t.Errorf("expected lifecycle/devops/%s bootstrapped by the scaffold run: %v", f, err)
		}
	}

	// The test env's repo was created by the harness, not by kaos-control
	// (unmanaged), so the generated files are surfaced as git commands to run
	// rather than auto-committed.
	result, _ := postData["result"].(map[string]any)
	if cmds, _ := result["git_commands"].([]any); len(cmds) == 0 {
		t.Errorf("expected git_commands for a pre-existing (unmanaged) repo, got result=%v", result)
	}
	if committed, _ := result["committed"].(bool); committed {
		t.Error("expected committed=false for an unmanaged repo")
	}
}

// TestWizardScaffoldGet_NoScaffolderRegistered_ReturnsUnavailable covers
// FR-17: with no Scaffolder wired in, GET .../wizard/scaffold reports
// available:false with an explanatory message rather than erroring.
func TestWizardScaffoldGet_NoScaffolderRegistered_ReturnsUnavailable(t *testing.T) {
	env := newTestEnv(t, wizardCatalogSeeds())

	resp := env.doRequest("GET",
		"/api/p/testproject/architecture/wizard/scaffold?architecture=modular-monolith&tech_stack=go-vue", nil)
	requireStatus(t, resp, 200)
	data := readJSON(t, resp)

	if available, _ := data["available"].(bool); available {
		t.Errorf("expected available=false with no Scaffolder registered, got %v", data)
	}
	msg, _ := data["message"].(string)
	if !strings.Contains(msg, "not yet available") {
		t.Errorf("expected an explanatory 'not yet available' message, got %q", msg)
	}
}

// TestWizardScaffoldPost_NoScaffolderRegistered_GracefulNoWrites covers
// FR-17: POST .../wizard/scaffold with no Scaffolder registered returns the
// same graceful not-available response and writes nothing under the project.
func TestWizardScaffoldPost_NoScaffolderRegistered_GracefulNoWrites(t *testing.T) {
	env := newTestEnv(t, wizardCatalogSeeds())
	before := countArchitectureTreeFiles(t, filepath.Join(env.projectRoot, "lifecycle", "architecture"))

	resp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{},
	})
	requireStatus(t, resp, 200)
	data := readJSON(t, resp)

	if available, _ := data["available"].(bool); available {
		t.Errorf("expected available=false with no Scaffolder registered, got %v", data)
	}

	after := countArchitectureTreeFiles(t, filepath.Join(env.projectRoot, "lifecycle", "architecture"))
	if after != before {
		t.Errorf("POST /wizard/scaffold wrote files under lifecycle/architecture/ with no Scaffolder registered: %d before, %d after", before, after)
	}
}

// TestWizardCommit_WithoutScaffolding_YieldsCompleteProject covers FR-17/
// FR-18: a wizard committed without ever touching the scaffold endpoints
// still produces the complete, valid outcome — promoted files, summary, and
// ADR-0001, with nothing scaffold-related expected or present.
func TestWizardCommit_WithoutScaffolding_YieldsCompleteProject(t *testing.T) {
	env := newTestEnv(t, wizardCatalogSeeds())

	resp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/commit",
		wizardCommitReq("architectures/modular-monolith.md", "tech-stacks/go-vue.md", nil, nil, nil))
	requireStatus(t, resp, 200)
	data := readJSON(t, resp)

	for _, key := range []string{"promoted_architecture", "promoted_tech_stack", "adr_path", "summary_path"} {
		if got, _ := data[key].(string); got == "" {
			t.Errorf("expected %s to be populated on commit, got empty", key)
		}
	}

	for _, want := range []string{
		"lifecycle/architecture/modular-monolith.md",
		"lifecycle/architecture/go-vue.md",
		"lifecycle/architecture/architecture-summary.md",
	} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, filepath.FromSlash(want))); err != nil {
			t.Errorf("expected %q to exist after commit: %v", want, err)
		}
	}
}

// TestWizardScaffoldGet_ReportsPresence covers FR-4: before any scaffold run
// the step's presence is false, and after a real run the same GET reports
// present=true for that step.
func TestWizardScaffoldGet_ReportsPresence(t *testing.T) {
	architecture.RegisterScaffolder(directives.Scaffolder{})
	t.Cleanup(func() { architecture.RegisterScaffolder(nil) })

	env := newTestEnvWithScaffold(t, nil)

	getBefore := env.doRequest("GET",
		"/api/p/testproject/architecture/wizard/scaffold?architecture=modular-monolith&tech_stack=go-vue", nil)
	requireStatus(t, getBefore, 200)
	beforeStep0 := firstScaffoldStep(t, readJSON(t, getBefore))
	if present, _ := beforeStep0["present"].(bool); present {
		t.Errorf("expected present=false before any run, got %v", beforeStep0)
	}

	commit := env.doRequest("POST", "/api/p/testproject/architecture/wizard/commit",
		wizardCommitReq("architectures/modular-monolith.md", "tech-stacks/go-vue.md", nil, nil, nil))
	requireStatus(t, commit, 200)
	commit.Body.Close()

	postResp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{{"step_key": "agent-directives", "selected": true}},
	})
	requireStatus(t, postResp, 200)
	postResp.Body.Close()

	getAfter := env.doRequest("GET",
		"/api/p/testproject/architecture/wizard/scaffold?architecture=modular-monolith&tech_stack=go-vue", nil)
	requireStatus(t, getAfter, 200)
	afterStep0 := firstScaffoldStep(t, readJSON(t, getAfter))
	if present, _ := afterStep0["present"].(bool); !present {
		t.Errorf("expected present=true after a run, got %v", afterStep0)
	}
}

// TestWizardScaffoldGet_AuthenticatedNonProductOwner_Allowed covers NFR-3:
// GET .../wizard/scaffold only requires an authenticated user, not the
// product-owner role that POST requires.
func TestWizardScaffoldGet_AuthenticatedNonProductOwner_Allowed(t *testing.T) {
	env := newTestEnv(t, nil)
	env.login("dev@test.local", "dev-pass-123")

	resp := env.doRequest("GET",
		"/api/p/testproject/architecture/wizard/scaffold?architecture=modular-monolith&tech_stack=go-vue", nil)
	requireStatus(t, resp, 200)
	resp.Body.Close()
}

// TestWizardScaffoldPost_NonProductOwner_Forbidden covers NFR-3: POST
// .../wizard/scaffold requires the product-owner role, and a rejected
// request writes nothing.
func TestWizardScaffoldPost_NonProductOwner_Forbidden(t *testing.T) {
	architecture.RegisterScaffolder(directives.Scaffolder{})
	t.Cleanup(func() { architecture.RegisterScaffolder(nil) })

	env := newTestEnvWithScaffold(t, nil)
	env.login("dev@test.local", "dev-pass-123")

	resp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{{"step_key": "agent-directives", "selected": true}},
	})
	requireStatus(t, resp, 403)
	resp.Body.Close()

	for _, f := range []string{"AGENTS.md", "CLAUDE.md"} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, f)); err == nil {
			t.Errorf("expected %s NOT written for a forbidden POST", f)
		}
	}
}

// TestWizardScaffoldPost_SelectedFalse_WritesNothing covers FR-9/FR-10/
// FR-11: a choice for the step with selected=false — the single-step
// scaffolder's stand-in for "nothing selected" — applies nothing and writes
// no files, contrasting with the selected=true run in
// TestWizardScaffold_DirectivesScaffolder_GeneratesDirectiveFiles above.
func TestWizardScaffoldPost_SelectedFalse_WritesNothing(t *testing.T) {
	architecture.RegisterScaffolder(directives.Scaffolder{})
	t.Cleanup(func() { architecture.RegisterScaffolder(nil) })

	env := newTestEnvWithScaffold(t, nil)

	commit := env.doRequest("POST", "/api/p/testproject/architecture/wizard/commit",
		wizardCommitReq("architectures/modular-monolith.md", "tech-stacks/go-vue.md", nil, nil, nil))
	requireStatus(t, commit, 200)
	commit.Body.Close()

	resp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{{"step_key": "agent-directives", "selected": false}},
	})
	requireStatus(t, resp, 200)
	data := readJSON(t, resp)
	result, _ := data["result"].(map[string]any)
	if applied, _ := result["applied"].([]any); len(applied) != 0 {
		t.Errorf("expected no applied files for selected=false, got %v", applied)
	}

	for _, f := range []string{"AGENTS.md", "CLAUDE.md"} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, f)); err == nil {
			t.Errorf("expected %s NOT written when the step is unselected", f)
		}
	}
	for _, f := range []string{"build.yaml", "lint.yaml", "test.yaml"} {
		if _, err := os.Stat(filepath.Join(env.projectRoot, "lifecycle", "devops", f)); err == nil {
			t.Errorf("expected lifecycle/devops/%s NOT bootstrapped when the step is unselected", f)
		}
	}
}

// TestWizardScaffoldPost_NoNewArchitectureTreeArtefacts covers NFR-5: a real
// scaffold run writes to the project root and lifecycle/devops/, not
// lifecycle/architecture/ — so the architecture tree's file count after
// commit is governed only by promotion, and a subsequent scaffold run adds
// nothing there for the index to pick up as a new artefact type.
func TestWizardScaffoldPost_NoNewArchitectureTreeArtefacts(t *testing.T) {
	architecture.RegisterScaffolder(directives.Scaffolder{})
	t.Cleanup(func() { architecture.RegisterScaffolder(nil) })

	env := newTestEnvWithScaffold(t, nil)

	commit := env.doRequest("POST", "/api/p/testproject/architecture/wizard/commit",
		wizardCommitReq("architectures/modular-monolith.md", "tech-stacks/go-vue.md", nil, nil, nil))
	requireStatus(t, commit, 200)
	commit.Body.Close()

	archDir := filepath.Join(env.projectRoot, "lifecycle", "architecture")
	before := countArchitectureTreeFiles(t, archDir)

	postResp := env.doRequest("POST", "/api/p/testproject/architecture/wizard/scaffold", map[string]any{
		"architecture": "modular-monolith",
		"tech_stack":   "go-vue",
		"choices":      []map[string]any{{"step_key": "agent-directives", "selected": true}},
	})
	requireStatus(t, postResp, 200)
	postResp.Body.Close()

	after := countArchitectureTreeFiles(t, archDir)
	if after != before {
		t.Errorf("expected scaffold run to leave lifecycle/architecture/ file count unchanged (governed by promotion only): before=%d after=%d", before, after)
	}
}

// firstScaffoldStep extracts steps[0] from a GET .../wizard/scaffold response body.
func firstScaffoldStep(t *testing.T, data map[string]any) map[string]any {
	t.Helper()
	steps, _ := data["steps"].([]any)
	if len(steps) == 0 {
		t.Fatalf("expected at least one scaffold step, got %v", data)
	}
	step, _ := steps[0].(map[string]any)
	return step
}
