// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build integration

package integration

// Milestone 2 — Init Scaffold: config template defaults
//
// Tests for the lifecycle/config.yaml generated by kaos-control init covering:
//   - idea-capture agent is present with driver "inline" and lifecycle/ideas write path
//   - kanban block has Backlog/In-Progress/Done columns with the expected statuses
//   - dashboard block has tracked_types containing requirement, idea, defect
//   - The generated config loads cleanly through config.LoadProject

import (
	"testing"

	"github.com/kaos-control/kaos-control/internal/config"
	"github.com/kaos-control/kaos-control/internal/initcmd"
)

// runInitInTempDir runs initcmd.Run in a fresh temp directory and returns
// the directory path. The test is fatally failed on any error.
func runInitInTempDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := initcmd.Run([]string{dir}); err != nil {
		t.Fatalf("initcmd.Run failed: %v", err)
	}
	return dir
}

// loadInitConfig runs init, then loads and returns the generated project config.
func loadInitConfig(t *testing.T) *config.Project {
	t.Helper()
	dir := runInitInTempDir(t)
	cfg, err := config.LoadProject(dir)
	if err != nil {
		t.Fatalf("config.LoadProject failed: %v", err)
	}
	return cfg
}

// TestInit_ConfigHasIdeaCaptureAgent verifies that the generated config
// includes an agent named "idea-capture" with driver "inline" and
// allowed_write_paths containing "lifecycle/ideas".
func TestInit_ConfigHasIdeaCaptureAgent(t *testing.T) {
	cfg := loadInitConfig(t)

	var found *config.AgentConfig
	for i := range cfg.Agents {
		if cfg.Agents[i].Name == "idea-capture" {
			found = &cfg.Agents[i]
			break
		}
	}
	if found == nil {
		names := make([]string, len(cfg.Agents))
		for i, a := range cfg.Agents {
			names[i] = a.Name
		}
		t.Fatalf("no agent named 'idea-capture' in generated config; agents: %v", names)
	}

	if found.Driver != "inline" {
		t.Errorf("idea-capture driver = %q, want %q", found.Driver, "inline")
	}

	hasPath := false
	for _, p := range found.AllowedPaths {
		if p == "lifecycle/ideas" {
			hasPath = true
			break
		}
	}
	if !hasPath {
		t.Errorf("idea-capture allowed_write_paths = %v, want to contain %q", found.AllowedPaths, "lifecycle/ideas")
	}
}

// TestInit_ConfigHasKanbanDefaults verifies that the generated config includes
// a kanban block with at least three columns:
//   - Backlog: statuses must include "draft"
//   - In-Progress: statuses must include "in-development" and "in-qa"
//   - Done: statuses must include "done"
func TestInit_ConfigHasKanbanDefaults(t *testing.T) {
	cfg := loadInitConfig(t)

	if cfg.Kanban == nil {
		t.Fatal("kanban config is nil in generated config")
	}
	if len(cfg.Kanban.Columns) < 3 {
		t.Fatalf("kanban.columns has %d column(s), want at least 3", len(cfg.Kanban.Columns))
	}

	findColumn := func(name string) *config.KanbanColumn {
		for i := range cfg.Kanban.Columns {
			if cfg.Kanban.Columns[i].Name == name {
				return &cfg.Kanban.Columns[i]
			}
		}
		return nil
	}
	hasStatus := func(col *config.KanbanColumn, status string) bool {
		for _, s := range col.Statuses {
			if s == status {
				return true
			}
		}
		return false
	}

	// Backlog → must contain "draft"
	backlog := findColumn("Backlog")
	if backlog == nil {
		t.Fatal("kanban column 'Backlog' not found in generated config")
	}
	if !hasStatus(backlog, "draft") {
		t.Errorf("Backlog column statuses = %v, want to contain 'draft'", backlog.Statuses)
	}

	// In-Progress → must contain "in-development" and "in-qa"
	inProgress := findColumn("In-Progress")
	if inProgress == nil {
		t.Fatal("kanban column 'In-Progress' not found in generated config")
	}
	for _, want := range []string{"in-development", "in-qa"} {
		if !hasStatus(inProgress, want) {
			t.Errorf("In-Progress column statuses = %v, want to contain %q", inProgress.Statuses, want)
		}
	}

	// Done → must contain "done"
	done := findColumn("Done")
	if done == nil {
		t.Fatal("kanban column 'Done' not found in generated config")
	}
	if !hasStatus(done, "done") {
		t.Errorf("Done column statuses = %v, want to contain 'done'", done.Statuses)
	}
}

// TestInit_ConfigHasDashboardDefaults verifies that the generated config
// includes a dashboard block with tracked_types containing at minimum
// "requirement", "idea", and "defect".
func TestInit_ConfigHasDashboardDefaults(t *testing.T) {
	cfg := loadInitConfig(t)

	for _, want := range []string{"requirement", "idea", "defect"} {
		found := false
		for _, typ := range cfg.Dashboard.TrackedTypes {
			if typ == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("dashboard.tracked_types = %v, want to contain %q", cfg.Dashboard.TrackedTypes, want)
		}
	}
}

// TestInit_ConfigParsesCleanly verifies that the generated lifecycle/config.yaml
// can be loaded through config.LoadProject without error. This catches any
// regression where template rendering produces a structurally invalid config.
func TestInit_ConfigParsesCleanly(t *testing.T) {
	dir := runInitInTempDir(t)
	if _, err := config.LoadProject(dir); err != nil {
		t.Fatalf("config.LoadProject returned error for generated config: %v", err)
	}
}
