// ── Kaos Control Sample Data ──
// Exported to window for use across all components

const KC_SAMPLE_ARTIFACTS = [
  {
    path: 'ideas/user-login.md',
    title: 'User Login',
    type: 'idea',
    status: 'done',
    lineage: 'user-login',
    labels: ['auth', 'security'],
    release: 'r-2026.05',
    sprint: null,
    assignees: [{ role: 'product-owner', who: 'keith@sinclair.org.au' }],
    parent: null,
    depends_on: [],
    blocks: ['requirements/user-login-2.md'],
    body: `## Problem\nUsers need a way to authenticate securely against the application before accessing any project data.\n\n## Acceptance Criteria\n- Email + password login\n- Session persists 24h\n- Failed attempts rate-limited`,
    updatedAt: '2026-04-10T09:15:00Z',
  },
  {
    path: 'requirements/user-login-2.md',
    title: 'User Login Requirements',
    type: 'ticket',
    status: 'approved',
    lineage: 'user-login',
    labels: ['auth', 'security'],
    release: 'r-2026.05',
    sprint: 's-2026-04-b',
    assignees: [{ role: 'product-owner', who: 'keith@sinclair.org.au' }],
    parent: 'ideas/user-login.md',
    depends_on: [],
    blocks: ['backend-plans/user-login-3.md', 'frontend-plans/user-login-4.md'],
    body: `## Overview\nFull authentication flow with local accounts using argon2id password hashing.\n\n## Requirements\n- Login form: email + password\n- Argon2id hashing, session cookie with Secure + HttpOnly\n- Rate limit: 5 attempts per 10 min per IP\n- Session TTL: 24h (configurable)`,
    updatedAt: '2026-04-12T14:22:00Z',
  },
  {
    path: 'backend-plans/user-login-3.md',
    title: 'User Login — Backend Plan',
    type: 'plan-backend',
    status: 'approved',
    lineage: 'user-login',
    labels: ['auth', 'go'],
    release: 'r-2026.05',
    sprint: 's-2026-04-b',
    assignees: [{ role: 'backend-planner', who: 'claude-planner' }],
    parent: 'requirements/user-login-2.md',
    depends_on: [],
    blocks: ['dev-plans/user-login-5.md'],
    body: `## Endpoints\n- \`POST /api/auth/login\` — validates credentials, issues session cookie\n- \`POST /api/auth/logout\` — clears session\n- \`GET /api/auth/me\` — returns current user + roles\n\n## Storage\nSQLite: \`users\` table with argon2id hash, \`sessions\` table with TTL.`,
    updatedAt: '2026-04-14T11:00:00Z',
  },
  {
    path: 'frontend-plans/user-login-4.md',
    title: 'User Login — Frontend Plan',
    type: 'plan-frontend',
    status: 'in-development',
    lineage: 'user-login',
    labels: ['auth', 'vue'],
    release: 'r-2026.05',
    sprint: 's-2026-04-b',
    assignees: [{ role: 'frontend-planner', who: 'claude-planner' }],
    parent: 'requirements/user-login-2.md',
    depends_on: [],
    blocks: [],
    body: `## Components\n- \`LoginView.vue\` — full-screen login form\n- \`LoginForm.vue\` — email/password with validation\n- \`useAuthStore\` — login(), logout(), fetchMe()\n\n## Behaviour\nRedirect to /projects on success; show inline error on 401.`,
    updatedAt: '2026-04-18T16:45:00Z',
  },
  {
    path: 'dev-plans/user-login-5.md',
    title: 'User Login — Dev Plan',
    type: 'plan-dev',
    status: 'draft',
    lineage: 'user-login',
    labels: ['auth', 'go', 'vue'],
    release: 'r-2026.05',
    sprint: 's-2026-04-b',
    assignees: [{ role: 'developer', who: 'local-dev' }],
    parent: 'backend-plans/user-login-3.md',
    depends_on: ['frontend-plans/user-login-4.md'],
    blocks: [],
    body: `## Implementation Order\n1. Backend auth handlers + argon2id\n2. SQLite schema migration\n3. Vue LoginView + store\n4. Integration test`,
    updatedAt: '2026-04-19T08:30:00Z',
  },
  {
    path: 'ideas/password-reset.md',
    title: 'Password Reset',
    type: 'idea',
    status: 'clarifying',
    lineage: 'password-reset',
    labels: ['auth'],
    release: null,
    sprint: null,
    assignees: [{ role: 'product-owner', who: 'keith@sinclair.org.au' }],
    parent: null,
    depends_on: [],
    blocks: [],
    body: `## Problem\nUsers who forget their password have no way to recover access.\n\n## Open Questions\n- Email-based or token-file? (local tool — email may not be available)\n- Should admin be able to reset for users?`,
    updatedAt: '2026-04-20T10:00:00Z',
  },
  {
    path: 'requirements/password-reset-2.md',
    title: 'Password Reset Requirements',
    type: 'ticket',
    status: 'planning',
    lineage: 'password-reset',
    labels: ['auth'],
    release: null,
    sprint: null,
    assignees: [{ role: 'product-owner', who: 'keith@sinclair.org.au' }],
    parent: 'ideas/password-reset.md',
    depends_on: ['requirements/user-login-2.md'],
    blocks: [],
    body: `## Overview\nAdmin-initiated password reset via CLI command. No email required for local installs.\n\n## Requirements\n- \`kaos-control users reset-password <email>\` generates a one-time link\n- Link expires in 1h`,
    updatedAt: '2026-04-22T09:00:00Z',
  },
  {
    path: 'ideas/graph-zoom-persist.md',
    title: 'Persist Graph Zoom & Camera',
    type: 'idea',
    status: 'draft',
    lineage: 'graph-zoom-persist',
    labels: ['graph', 'ux'],
    release: null,
    sprint: null,
    assignees: [],
    parent: null,
    depends_on: [],
    blocks: [],
    body: `## Problem\nEvery page load resets the 3D graph camera to default position, losing context.\n\n## Proposal\nSave camera position to localStorage per project.`,
    updatedAt: '2026-04-23T15:00:00Z',
  },
  {
    path: 'ideas/dashboard-redesign.md',
    title: 'Project Dashboard Redesign',
    type: 'epic',
    status: 'in-development',
    lineage: 'dashboard-redesign',
    labels: ['ux', 'graph'],
    release: 'r-2026.06',
    sprint: null,
    assignees: [{ role: 'frontend-planner', who: 'claude-planner' }],
    parent: null,
    depends_on: [],
    blocks: [],
    body: `## Vision\nA summary dashboard view aggregating sprint progress, open blockers, and agent activity.\n\n## Scope\nCross-sprint, cross-lineage summary. No graph — table + charts.`,
    updatedAt: '2026-04-21T11:00:00Z',
  },
  {
    path: 'releases/r-2026.05.md',
    title: 'Release r-2026.05',
    type: 'release',
    status: 'planning',
    lineage: 'r-2026.05',
    labels: [],
    release: null,
    sprint: null,
    assignees: [{ role: 'approver', who: 'keith@sinclair.org.au' }],
    parent: null,
    depends_on: [],
    blocks: [],
    body: `## Members\n- [[requirements/user-login-2]]\n- [[backend-plans/user-login-3]]\n- [[frontend-plans/user-login-4]]\n- [[dev-plans/user-login-5]]\n\n## Target date: 2026-05-15`,
    updatedAt: '2026-04-15T09:00:00Z',
  },
  {
    path: 'sprints/s-2026-04-b.md',
    title: 'Sprint s-2026-04-b',
    type: 'sprint',
    status: 'in-development',
    lineage: 's-2026-04-b',
    labels: [],
    release: null,
    sprint: null,
    assignees: [],
    parent: null,
    depends_on: [],
    blocks: [],
    body: `## Dates\n2026-04-14 → 2026-04-25\n\n## Members\n- [[requirements/user-login-2]]\n- [[backend-plans/user-login-3]]\n- [[frontend-plans/user-login-4]]\n- [[dev-plans/user-login-5]]`,
    updatedAt: '2026-04-14T08:00:00Z',
  },
];

const KC_SAMPLE_LINKS = [
  { source: 'ideas/user-login.md',            target: 'requirements/user-login-2.md',    kind: 'parent' },
  { source: 'requirements/user-login-2.md',   target: 'backend-plans/user-login-3.md',   kind: 'parent' },
  { source: 'requirements/user-login-2.md',   target: 'frontend-plans/user-login-4.md',  kind: 'parent' },
  { source: 'backend-plans/user-login-3.md',  target: 'dev-plans/user-login-5.md',       kind: 'parent' },
  { source: 'ideas/password-reset.md',        target: 'requirements/password-reset-2.md',kind: 'parent' },
  { source: 'requirements/password-reset-2.md',target:'requirements/user-login-2.md',    kind: 'depends_on' },
  { source: 'frontend-plans/user-login-4.md', target: 'dev-plans/user-login-5.md',       kind: 'depends_on' },
  { source: 'releases/r-2026.05.md',          target: 'requirements/user-login-2.md',    kind: 'member_of' },
  { source: 'releases/r-2026.05.md',          target: 'backend-plans/user-login-3.md',   kind: 'member_of' },
  { source: 'releases/r-2026.05.md',          target: 'frontend-plans/user-login-4.md',  kind: 'member_of' },
  { source: 'releases/r-2026.05.md',          target: 'dev-plans/user-login-5.md',       kind: 'member_of' },
  { source: 'sprints/s-2026-04-b.md',         target: 'requirements/user-login-2.md',    kind: 'member_of' },
  { source: 'sprints/s-2026-04-b.md',         target: 'backend-plans/user-login-3.md',   kind: 'member_of' },
  { source: 'sprints/s-2026-04-b.md',         target: 'frontend-plans/user-login-4.md',  kind: 'member_of' },
];

const KC_SAMPLE_AGENTS = [
  {
    id: 'run-001',
    agent: 'claude-planner',
    role: 'frontend-planner',
    target: 'frontend-plans/user-login-4.md',
    status: 'running',
    startedAt: '2026-04-24T10:32:00Z',
    pct: 67,
    lastMessage: 'Writing FrontmatterPanel component spec…',
  },
  {
    id: 'run-002',
    agent: 'claude-planner',
    role: 'backend-planner',
    target: 'backend-plans/user-login-3.md',
    status: 'finished',
    startedAt: '2026-04-24T09:10:00Z',
    finishedAt: '2026-04-24T09:18:00Z',
    artifactsProduced: ['backend-plans/user-login-3.md'],
    commit: 'a3f9c12',
  },
  {
    id: 'run-003',
    agent: 'local-dev',
    role: 'developer',
    target: 'dev-plans/user-login-5.md',
    status: 'crashed',
    startedAt: '2026-04-23T16:00:00Z',
    finishedAt: '2026-04-23T16:04:00Z',
    exitCode: 1,
    stderrTail: 'Error: model context limit exceeded',
  },
];

const KC_SAMPLE_PROJECTS = [
  { name: 'customer-portal', description: 'Customer portal rewrite', path: '/home/keith/Projects/customer-portal', owner: 'keith@sinclair.org.au', artifactCount: 11 },
  { name: 'data-pipeline', description: 'ETL pipeline for analytics', path: '/home/keith/Projects/data-pipeline', owner: 'keith@sinclair.org.au', artifactCount: 4 },
  { name: 'mobile-app-v2', description: 'React Native mobile app, second gen', path: '/home/keith/Projects/mobile-app-v2', owner: 'keith@sinclair.org.au', artifactCount: 18 },
];

const TYPE_COLORS = {
  'idea':          'var(--node-idea)',
  'ticket':        'var(--node-ticket)',
  'epic':          'var(--node-epic)',
  'plan-backend':  'var(--node-plan-backend)',
  'plan-frontend': 'var(--node-plan-frontend)',
  'plan-dev':      'var(--node-plan-dev)',
  'plan-test':     'var(--node-plan-test)',
  'release':       'var(--node-release)',
  'sprint':        'var(--node-sprint)',
  'test':          'var(--node-test)',
  'prototype':     'var(--node-prototype)',
};

const STATUS_COLORS = {
  'draft':          'var(--status-draft)',
  'clarifying':     'var(--status-clarifying)',
  'planning':       'var(--status-planning)',
  'in-development': 'var(--status-in-development)',
  'in-qa':          'var(--status-in-qa)',
  'approved':       'var(--status-approved)',
  'rejected':       'var(--status-rejected)',
  'abandoned':      'var(--status-abandoned)',
  'done':           'var(--status-done)',
};

const EDGE_COLORS = {
  'parent':     'oklch(0.65 0.15 280)',
  'depends_on': 'oklch(0.70 0.20 50)',
  'blocks':     'oklch(0.60 0.22 22)',
  'member_of':  'oklch(0.65 0.15 192)',
  'related_to': 'oklch(0.55 0.08 280)',
};

Object.assign(window, {
  KC_SAMPLE_ARTIFACTS,
  KC_SAMPLE_LINKS,
  KC_SAMPLE_AGENTS,
  KC_SAMPLE_PROJECTS,
  TYPE_COLORS,
  STATUS_COLORS,
  EDGE_COLORS,
});
